config/routes.rb
MediaGO::Application.routes.draw do
  resources :paginas

root :to => 'paginas#index'
 resources :paginas

  

end

app/models/pagina.rb
class Pagina < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController
  before_action :set_pagina, only: [:show, :edit, :update, :destroy]

  # GET /paginas
  # GET /paginas.json
  def index
    @paginas = Pagina.all
  end

  # GET /paginas/1
  # GET /paginas/1.json
  def show
  end

  # GET /paginas/new
  def new
    @pagina = Pagina.new
  end

  # GET /paginas/1/edit
  def edit
  end

  # POST /paginas
  # POST /paginas.json
  def create
    @pagina = Pagina.new(pagina_params)

    respond_to do |format|
      if @pagina.save
        format.html { redirect_to @pagina, notice: 'Pagina was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pagina }
      else
        format.html { render action: 'new' }
        format.json { render json: @pagina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paginas/1
  # PATCH/PUT /paginas/1.json
  def update
    respond_to do |format|
      if @pagina.update(pagina_params)
        format.html { redirect_to @pagina, notice: 'Pagina was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pagina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paginas/1
  # DELETE /paginas/1.json
  def destroy
    @pagina.destroy
    respond_to do |format|
      format.html { redirect_to paginas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pagina
      @pagina = Pagina.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pagina_params
      params.require(:pagina).permit(:principal)
    end
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

 <title>Media Go</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Bootstrap -->
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,700,900,300,100' rel='stylesheet' type='text/css'>

<%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
  <body>
 
   <div class="jumbotron">
 <h1>A Santiago le falta Rock</h1>    
<h2>Pronto las calles tendrán otro color</h2>
</div>
  <div class="container"> 
    <div class="row">
            <div class="col-md-4 col-sm-offset-4">
  <form class="margin-base-vertical">
<p class="input-group">
  <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></span>
    <input type="text" class="form-control input-sm" name="email" placeholder="erik@whatever.com" />
</p>
 <p class="help-block text-center"><small>Tranquilo, no te vamos a llenar de spam.</small></p>
                    <p class="text-center">
                        <button type="submit" class="btn btn-primary btn-md">Manténme al tanto</button>
                    </p>
                    </span>
                </form>
</div>
</div>
  </div>
</div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>

  </body>
</html>

app/views/paginas/_form.html.erb
<%= form_for(@pagina) do |f| %>
  <% if @pagina.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pagina.errors.count, "error") %> prohibited this pagina from being saved:</h2>

      <ul>
      <% @pagina.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :principal %><br>
    <%= f.text_field :principal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paginas/edit.html.erb
<h1>Editing pagina</h1>

<%= render 'form' %>

<%= link_to 'Show', @pagina %> |
<%= link_to 'Back', paginas_path %>

app/views/paginas/index.html.erb
<h1>Listing paginas</h1>

<table>
  <thead>
    <tr>
      <th>Principal</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @paginas.each do |pagina| %>
      <tr>
        <td><%= pagina.principal %></td>
        <td><%= link_to 'Show', pagina %></td>
        <td><%= link_to 'Edit', edit_pagina_path(pagina) %></td>
        <td><%= link_to 'Destroy', pagina, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pagina', new_pagina_path %>

app/views/paginas/new.html.erb
<h1>New pagina</h1>

<%= render 'form' %>

<%= link_to 'Back', paginas_path %>

app/views/paginas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Principal:</strong>
  <%= @pagina.principal %>
</p>

<%= link_to 'Edit', edit_pagina_path(@pagina) %> |
<%= link_to 'Back', paginas_path %>